ALTER TABLE employees
ADD password VARCHAR(20) NOT null;
UPDATE employees SET password = 'PSWD1' WHERE employeeNumber = 10 ;
UPDATE employees SET password = 'PSWD2' WHERE employeeNumber = 110 ;
UPDATE employees SET password = 'PSWD3' WHERE employeeNumber = 210 ;
UPDATE employees SET password = 'PSWD4' WHERE employeeNumber = 1002 ;
UPDATE employees SET password = 'PSWD5' WHERE employeeNumber = 1034 ;
UPDATE employees SET password = 'PSWD6' WHERE employeeNumber = 1056 ;
UPDATE employees SET password = 'PSWD7' WHERE employeeNumber = 1076 ;
UPDATE employees SET password = 'PSWD8' WHERE employeeNumber = 1088 ;
UPDATE employees SET password = 'PSWD9' WHERE employeeNumber = 1102 ;
UPDATE employees SET password = 'PSWD10' WHERE employeeNumber = 1143 ;
UPDATE employees SET password = 'PSWD11' WHERE employeeNumber = 1165 ;
UPDATE employees SET password = 'PSWD12' WHERE employeeNumber = 1166 ;
UPDATE employees SET password = 'PSWD13' WHERE employeeNumber = 1188 ;
UPDATE employees SET password = 'PSWD14' WHERE employeeNumber = 1216;
UPDATE employees SET password = 'PSWD15' WHERE employeeNumber = 1286 ;
UPDATE employees SET password = 'PSWD16' WHERE employeeNumber = 1323;
UPDATE employees SET password = 'PSWD17' WHERE employeeNumber = 1337 ;
UPDATE employees SET password = 'PSWD18' WHERE employeeNumber = 1370 ;
UPDATE employees SET password = 'PSWD19' WHERE employeeNumber = 1401 ;
UPDATE employees SET password = 'PSWD20' WHERE employeeNumber = 1501;
UPDATE employees SET password = 'PSWD21' WHERE employeeNumber = 1504 ;
UPDATE employees SET password = 'PSWD22' WHERE employeeNumber = 1611 ;
UPDATE employees SET password = 'PSWD23' WHERE employeeNumber = 1612;
UPDATE employees SET password = 'PSWD24' WHERE employeeNumber = 1619;
UPDATE employees SET password = 'PSWD25' WHERE employeeNumber = 1621;
UPDATE employees SET password = 'PSWD26' WHERE employeeNumber = 1625;
UPDATE employees SET password = 'PSWD27' WHERE employeeNumber = 1702;