// Code generated by mockery v2.7.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/subodhqss/go-training/models"
)

// CustomerReposiotry is an autogenerated mock type for the CustomerReposiotry type
type CustomerReposiotry struct {
	mock.Mock
}

// PrintCustomer provides a mock function with given fields:
func (_m *CustomerReposiotry) PrintCustomer() []*models.Customer {
	ret := _m.Called()

	var r0 []*models.Customer
	if rf, ok := ret.Get(0).(func() []*models.Customer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Customer)
		}
	}

	return r0
}

// PrintCustomerId provides a mock function with given fields: _a0
func (_m *CustomerReposiotry) PrintCustomerId(_a0 string) *models.Customer {
	ret := _m.Called(_a0)

	var r0 *models.Customer
	if rf, ok := ret.Get(0).(func(string) *models.Customer); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Customer)
		}
	}

	return r0
}

// SaveCustomer provides a mock function with given fields: _a0
func (_m *CustomerReposiotry) SaveCustomer(_a0 models.Customer) *models.Customer {
	ret := _m.Called(_a0)

	var r0 *models.Customer
	if rf, ok := ret.Get(0).(func(models.Customer) *models.Customer); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Customer)
		}
	}

	return r0
}

// UpdateC provides a mock function with given fields: _a0
func (_m *CustomerReposiotry) UpdateC(_a0 models.Customer) *models.Customer {
	ret := _m.Called(_a0)

	var r0 *models.Customer
	if rf, ok := ret.Get(0).(func(models.Customer) *models.Customer); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Customer)
		}
	}

	return r0
}

// UpdateCustomer provides a mock function with given fields: _a0
func (_m *CustomerReposiotry) UpdateCustomer(_a0 models.Customer) *models.Customer {
	ret := _m.Called(_a0)

	var r0 *models.Customer
	if rf, ok := ret.Get(0).(func(models.Customer) *models.Customer); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Customer)
		}
	}

	return r0
}
