// Code generated by mockery v2.7.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/subodhqss/go-training/models"
)

// EmployeReposiotry is an autogenerated mock type for the EmployeReposiotry type
type EmployeReposiotry struct {
	mock.Mock
}

// DeleteEmployee provides a mock function with given fields: _a0, _a1
func (_m *EmployeReposiotry) DeleteEmployee(_a0 models.Employee, _a1 string) *models.Employee {
	ret := _m.Called(_a0, _a1)

	var r0 *models.Employee
	if rf, ok := ret.Get(0).(func(models.Employee, string) *models.Employee); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Employee)
		}
	}

	return r0
}

// PrintEmploye provides a mock function with given fields:
func (_m *EmployeReposiotry) PrintEmploye() []*models.Employee {
	ret := _m.Called()

	var r0 []*models.Employee
	if rf, ok := ret.Get(0).(func() []*models.Employee); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Employee)
		}
	}

	return r0
}

// PrintEmployeId provides a mock function with given fields: _a0
func (_m *EmployeReposiotry) PrintEmployeId(_a0 string) *models.Employee {
	ret := _m.Called(_a0)

	var r0 *models.Employee
	if rf, ok := ret.Get(0).(func(string) *models.Employee); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Employee)
		}
	}

	return r0
}

// SaveEmployee provides a mock function with given fields: _a0
func (_m *EmployeReposiotry) SaveEmployee(_a0 models.Employee) *models.Employee {
	ret := _m.Called(_a0)

	var r0 *models.Employee
	if rf, ok := ret.Get(0).(func(models.Employee) *models.Employee); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Employee)
		}
	}

	return r0
}

// Update provides a mock function with given fields: _a0
func (_m *EmployeReposiotry) Update(_a0 models.Employee) *models.Employee {
	ret := _m.Called(_a0)

	var r0 *models.Employee
	if rf, ok := ret.Get(0).(func(models.Employee) *models.Employee); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Employee)
		}
	}

	return r0
}

// UpdateEmployee provides a mock function with given fields: _a0
func (_m *EmployeReposiotry) UpdateEmployee(_a0 models.Employee) *models.Employee {
	ret := _m.Called(_a0)

	var r0 *models.Employee
	if rf, ok := ret.Get(0).(func(models.Employee) *models.Employee); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Employee)
		}
	}

	return r0
}

// UpdateImage provides a mock function with given fields: _a0, _a1, _a2
func (_m *EmployeReposiotry) UpdateImage(_a0 string, _a1 string, _a2 string) *models.Employee {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *models.Employee
	if rf, ok := ret.Get(0).(func(string, string, string) *models.Employee); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Employee)
		}
	}

	return r0
}
