// Code generated by mockery v2.7.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/subodhqss/go-training/models"
)

// loginService is an autogenerated mock type for the loginService type
type loginService struct {
	mock.Mock
}

// LoginEmployee provides a mock function with given fields: login
func (_m *loginService) LoginEmployee(login *models.Login) *models.Login {
	ret := _m.Called(login)

	var r0 *models.Login
	if rf, ok := ret.Get(0).(func(*models.Login) *models.Login); ok {
		r0 = rf(login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Login)
		}
	}

	return r0
}
