// Code generated by mockery v2.7.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/subodhqss/go-training/models"
)

// OfficeReposiotry is an autogenerated mock type for the OfficeReposiotry type
type OfficeReposiotry struct {
	mock.Mock
}

// PrintOffice provides a mock function with given fields:
func (_m *OfficeReposiotry) PrintOffice() []*models.Office {
	ret := _m.Called()

	var r0 []*models.Office
	if rf, ok := ret.Get(0).(func() []*models.Office); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Office)
		}
	}

	return r0
}

// PrintOfficeId provides a mock function with given fields: _a0
func (_m *OfficeReposiotry) PrintOfficeId(_a0 string) *models.Office {
	ret := _m.Called(_a0)

	var r0 *models.Office
	if rf, ok := ret.Get(0).(func(string) *models.Office); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Office)
		}
	}

	return r0
}

// SaveOffice provides a mock function with given fields: _a0
func (_m *OfficeReposiotry) SaveOffice(_a0 models.Office) *models.Office {
	ret := _m.Called(_a0)

	var r0 *models.Office
	if rf, ok := ret.Get(0).(func(models.Office) *models.Office); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Office)
		}
	}

	return r0
}

// UpdateOffice provides a mock function with given fields: _a0
func (_m *OfficeReposiotry) UpdateOffice(_a0 models.Office) *models.Office {
	ret := _m.Called(_a0)

	var r0 *models.Office
	if rf, ok := ret.Get(0).(func(models.Office) *models.Office); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Office)
		}
	}

	return r0
}
