// Code generated by mockery v2.7.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/subodhqss/go-training/models"
)

// OrderDetailReposiotry is an autogenerated mock type for the OrderDetailReposiotry type
type OrderDetailReposiotry struct {
	mock.Mock
}

// PrintOrderDetail provides a mock function with given fields:
func (_m *OrderDetailReposiotry) PrintOrderDetail() []*models.Orderdetail {
	ret := _m.Called()

	var r0 []*models.Orderdetail
	if rf, ok := ret.Get(0).(func() []*models.Orderdetail); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Orderdetail)
		}
	}

	return r0
}

// PrintOrderDetailId provides a mock function with given fields: _a0
func (_m *OrderDetailReposiotry) PrintOrderDetailId(_a0 string) *models.Orderdetail {
	ret := _m.Called(_a0)

	var r0 *models.Orderdetail
	if rf, ok := ret.Get(0).(func(string) *models.Orderdetail); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Orderdetail)
		}
	}

	return r0
}

// SaveOrderDetail provides a mock function with given fields: _a0
func (_m *OrderDetailReposiotry) SaveOrderDetail(_a0 models.Orderdetail) *models.Orderdetail {
	ret := _m.Called(_a0)

	var r0 *models.Orderdetail
	if rf, ok := ret.Get(0).(func(models.Orderdetail) *models.Orderdetail); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Orderdetail)
		}
	}

	return r0
}

// UpdateOrderDetail provides a mock function with given fields: _a0
func (_m *OrderDetailReposiotry) UpdateOrderDetail(_a0 models.Orderdetail) *models.Orderdetail {
	ret := _m.Called(_a0)

	var r0 *models.Orderdetail
	if rf, ok := ret.Get(0).(func(models.Orderdetail) *models.Orderdetail); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Orderdetail)
		}
	}

	return r0
}
