// Code generated by mockery v2.7.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/subodhqss/go-training/models"
)

// OrderdetailReposiotry is an autogenerated mock type for the OrderdetailReposiotry type
type OrderdetailReposiotry struct {
	mock.Mock
}

// PrintOrderdetail provides a mock function with given fields:
func (_m *OrderdetailReposiotry) PrintOrderdetail() []*models.Orderdetail {
	ret := _m.Called()

	var r0 []*models.Orderdetail
	if rf, ok := ret.Get(0).(func() []*models.Orderdetail); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Orderdetail)
		}
	}

	return r0
}

// SaveDetail provides a mock function with given fields: _a0
func (_m *OrderdetailReposiotry) SaveDetail(_a0 models.Orderdetail) *models.Orderdetail {
	ret := _m.Called(_a0)

	var r0 *models.Orderdetail
	if rf, ok := ret.Get(0).(func(models.Orderdetail) *models.Orderdetail); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Orderdetail)
		}
	}

	return r0
}

// UpdateD provides a mock function with given fields: _a0
func (_m *OrderdetailReposiotry) UpdateD(_a0 models.Orderdetail) *models.Orderdetail {
	ret := _m.Called(_a0)

	var r0 *models.Orderdetail
	if rf, ok := ret.Get(0).(func(models.Orderdetail) *models.Orderdetail); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Orderdetail)
		}
	}

	return r0
}

// UpdateDetail provides a mock function with given fields: _a0
func (_m *OrderdetailReposiotry) UpdateDetail(_a0 models.Orderdetail) *models.Orderdetail {
	ret := _m.Called(_a0)

	var r0 *models.Orderdetail
	if rf, ok := ret.Get(0).(func(models.Orderdetail) *models.Orderdetail); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Orderdetail)
		}
	}

	return r0
}
