// Code generated by mockery v2.7.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/subodhqss/go-training/models"
)

// PaymentReposiotry is an autogenerated mock type for the PaymentReposiotry type
type PaymentReposiotry struct {
	mock.Mock
}

// PrintPayment provides a mock function with given fields:
func (_m *PaymentReposiotry) PrintPayment() []*models.Payment {
	ret := _m.Called()

	var r0 []*models.Payment
	if rf, ok := ret.Get(0).(func() []*models.Payment); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Payment)
		}
	}

	return r0
}

// SavePayment provides a mock function with given fields: _a0
func (_m *PaymentReposiotry) SavePayment(_a0 models.Payment) *models.Payment {
	ret := _m.Called(_a0)

	var r0 *models.Payment
	if rf, ok := ret.Get(0).(func(models.Payment) *models.Payment); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Payment)
		}
	}

	return r0
}

// UpdatePa provides a mock function with given fields: _a0
func (_m *PaymentReposiotry) UpdatePa(_a0 models.Payment) *models.Payment {
	ret := _m.Called(_a0)

	var r0 *models.Payment
	if rf, ok := ret.Get(0).(func(models.Payment) *models.Payment); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Payment)
		}
	}

	return r0
}

// UpdatePayment provides a mock function with given fields: _a0
func (_m *PaymentReposiotry) UpdatePayment(_a0 models.Payment) *models.Payment {
	ret := _m.Called(_a0)

	var r0 *models.Payment
	if rf, ok := ret.Get(0).(func(models.Payment) *models.Payment); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Payment)
		}
	}

	return r0
}
