// Code generated by mockery v2.7.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/subodhqss/go-training/models"
)

// ProductlineService is an autogenerated mock type for the ProductlineService type
type ProductlineService struct {
	mock.Mock
}

// PrintProductline provides a mock function with given fields:
func (_m *ProductlineService) PrintProductline() []*models.Productline {
	ret := _m.Called()

	var r0 []*models.Productline
	if rf, ok := ret.Get(0).(func() []*models.Productline); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Productline)
		}
	}

	return r0
}

// SaveProductline provides a mock function with given fields: _a0
func (_m *ProductlineService) SaveProductline(_a0 models.Productline) *models.Productline {
	ret := _m.Called(_a0)

	var r0 *models.Productline
	if rf, ok := ret.Get(0).(func(models.Productline) *models.Productline); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Productline)
		}
	}

	return r0
}

// UpdateProductline provides a mock function with given fields: _a0
func (_m *ProductlineService) UpdateProductline(_a0 models.Productline) *models.Productline {
	ret := _m.Called(_a0)

	var r0 *models.Productline
	if rf, ok := ret.Get(0).(func(models.Productline) *models.Productline); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Productline)
		}
	}

	return r0
}
