// Code generated by mockery v2.7.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/subodhqss/go-training/models"
)

// TestService is an autogenerated mock type for the TestService type
type TestService struct {
	mock.Mock
}

// PrintTest provides a mock function with given fields:
func (_m *TestService) PrintTest() *models.Test {
	ret := _m.Called()

	var r0 *models.Test
	if rf, ok := ret.Get(0).(func() *models.Test); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Test)
		}
	}

	return r0
}
